language: csharp
solution: ASPWiki.sln
install:
  - nuget restore ASPWiki.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ASPWiki.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./test/bin/Release/netcoreapp1.0/test.dll